//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPoll
    {
        public short Id { get; set; }
        public short UserId { get; set; }
        public short PollId { get; set; }
    
        public virtual Poll Poll { get; set; }
        public virtual User User { get; set; }
    }
}
